<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BuildingBlocks.Shared\BuildingBlocks.Shared.csproj" />
      <ProjectReference Include="..\QuizService.Domain\QuizService.Domain.csproj" />
      <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.Redis\BuildingBlocks.Redis.csproj" />
      <ProjectReference Include="..\..\BuildingBlocks\BuildingBlock.UserContextMiddleware\BuildingBlock.UserContextMiddleware.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JWT" Version="9.0.3" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.17" />
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.1" />
    </ItemGroup>

</Project>
