services:
  notification.server:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService.WebApi/Dockerfile
    ports:
      - "5005:5005"
      - "5006:5006"
    env_file:
      - .env
    restart: always