services:
  user.server:
    image: ${DOCKER_REGISTRY-}usersevice
    build:
      context: .
      dockerfile: UserService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    ports:
      - "5003:5003"
      - "5004:5004"
    env_file:
      - .env
    restart: always

  
volumes:
  postgres_data:
    driver: local
