# yaml
services:
  auth.server:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authservice;Username=postgres;Password=postgres
    ports:
      - "5002:8080"
    depends_on:
        - postgres
    env_file:
      - ../../.env
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: authservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  auth-db-data:
    external: true
