# yaml
services:
  auth.server:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
      - "5002:5002"
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
    driver: local
