name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write
  contents: read

 

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      AZURESTORAGE__CONNECTIONSTRING: ${{ secrets.AZURESTORAGE__CONNECTIONSTRING }}
      ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}
      REDISENDPOINT: ${{ secrets.REDISENDPOINT }}
      REDISPASSWORD: ${{ secrets.REDISPASSWORD }}
      REDISUSER: ${{ secrets.REDISUSER }}
      SMTPSETTINGS__ENABLESSL: ${{ secrets.SMTPSETTINGS__ENABLESSL }}
      SMTPSETTINGS__HOST: ${{ secrets.SMTPSETTINGS__HOST }}
      SMTPSETTINGS__PASSWORD: ${{ secrets.SMTPSETTINGS__PASSWORD }}
      SMTPSETTINGS__PORT: ${{ secrets.SMTPSETTINGS__PORT }}
      SMTPSETTINGS__SENDEREMAIL: ${{ secrets.SMTPSETTINGS__SENDEREMAIL }}
      SMTPSETTINGS__USERNAME: ${{ secrets.SMTPSETTINGS__USERNAME }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Change this to match your SDK version

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean the solution
        run: dotnet clean

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'Test Results'
          path: 'TestResults/*.trx'
          reporter: dotnet-trx
    